AllCops:
  NewCops: enable
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/RaiseArgs:
  Enabled: false
Style/TrivialAccessors:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/RegexpLiteral:
  AllowInnerSlashes: true
Style/MethodCallWithoutArgsParentheses:
  Enabled: false
Style/RescueStandardError:
  Enabled: false
Style/SafeNavigation:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/RedundantFileExtensionInRequire:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Metrics/ModuleLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space
Layout/ParameterAlignment:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Layout/FirstArrayElementIndentation:
  Enabled: false
Layout/FirstHashElementIndentation:
  Enabled: false
Layout/CaseIndentation:
  Enabled: false
Layout/EndAlignment:
  Enabled: false
Layout/DotPosition:
  EnforcedStyle: leading
Layout/LineLength:
  Enabled: false
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Naming/RescuedExceptionsVariableName:
  Enabled: false
Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/DuplicateElsifCondition:
  Enabled: true
Lint/DuplicateRescueException:
  Enabled: true
Lint/EmptyConditionalBody:
  Enabled: true
