#! /bin/bash

DESTINATION_PATH=~/.dotfiles/

cp ~/bin/dotfiles ${DESTINATION_PATH}dotfiles
cp ~/.bash_profile ${DESTINATION_PATH}.bash_profile
cp ~/.zshrc ${DESTINATION_PATH}.zshrc
cp ~/.vimrc ${DESTINATION_PATH}.vimrc
cp -r ~/.vim/colors ${DESTINATION_PATH}.vim/
cp ~/.tmux.conf ${DESTINATION_PATH}.tmux.conf
cp ~/.alacritty.yml ${DESTINATION_PATH}.alacritty.yml
cp ~/.prettierrc.json ${DESTINATION_PATH}.prettierrc.json
cp ~/.rubocop.yml ${DESTINATION_PATH}.rubocop.yml
cp ~/.gemrc ${DESTINATION_PATH}.gemrc
cp ~/.gitconfig ${DESTINATION_PATH}.gitconfig
cp ~/.gitignore_global ${DESTINATION_PATH}.gitignore_global
cp ~/.gitattributes ${DESTINATION_PATH}.gitattributes
